-- Create the contact_messages table
CREATE TABLE IF NOT EXISTS contact_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  full_name TEXT NOT NULL,
  institution TEXT,
  email TEXT,
  interest_type TEXT,
  consultation_channel TEXT,
  message TEXT,
  status TEXT DEFAULT 'new' -- new, read, archived
);

-- Enable Row Level Security (RLS)
ALTER TABLE contact_messages ENABLE ROW LEVEL SECURITY;

-- Policy 1: Allow anyone (anon) to INSERT messages
DROP POLICY IF EXISTS "Allow public inserts" ON contact_messages;
CREATE POLICY "Allow public inserts" 
ON contact_messages 
FOR INSERT 
TO anon 
WITH CHECK (true);

-- Policy 2: Allow only authenticated users (service_role or admin) to READ messages
DROP POLICY IF EXISTS "Allow authenticated reads" ON contact_messages;
CREATE POLICY "Allow authenticated reads" 
ON contact_messages 
FOR SELECT 
TO authenticated 
USING (true);

-- Optional: Allow authenticated users to update status
DROP POLICY IF EXISTS "Allow authenticated updates" ON contact_messages;
CREATE POLICY "Allow authenticated updates" 
ON contact_messages 
FOR UPDATE 
TO authenticated 
USING (true);
